# Generated by Django 6.0.5 on 2026-06-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0002_remove_event_participants_event_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_associations', to='gifting.wishlist'),
        ),
    ]
