# Generated by Django 6.0.5 on 2026-06-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0003_alter_eventparticipant_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('secret_santa', 'Secret Santa'), ('birthday', 'Birthday'), ('general', 'General')], default='secret_santa', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='gifting.eventparticipant')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='gifting.eventparticipant')),
            ],
        ),
    ]
